// Bundled Quran text dump loader.
//
// The app ships a static `quran-dump.json` (generated by
// `pnpm --filter @workspace/scripts run build-quran-dump`) under the
// artifact's public folder so it serves over the same origin and works
// fully offline once cached by the browser. This means a self-hosted
// instance does NOT need any external Quran API to function — the
// alquran.cloud API is kept only as a last-resort fallback.
//
// The dump is fetched lazily (and only once per session) the first time
// any page is requested that isn't already in IndexedDB.

import type { ApiAyah } from "@/hooks/use-page-ayahs";

interface DumpFile {
  version: number;
  edition: string;
  source: string;
  pages: Record<string, ApiAyah[]>;
}

let dumpPromise: Promise<DumpFile | null> | null = null;

/**
 * Drop the memoised promise so the next `getDump()` call retries the
 * fetch. Used by `resetAyahIndex()` and any error UI that wants to give
 * the user a "Retry" button after a transient failure (rather than
 * forcing a full SPA reload).
 */
export function resetDumpCache(): void {
  dumpPromise = null;
}

function dumpUrl(): string {
  // BASE_URL is injected by Vite and includes a trailing slash. Using it
  // means the dump is fetched relative to whatever path the artifact is
  // mounted at, both in dev (proxied) and in production deployments.
  const base = import.meta.env.BASE_URL ?? "/";
  return `${base}quran-dump.json`;
}

async function loadDump(): Promise<DumpFile | null> {
  try {
    const res = await fetch(dumpUrl(), { cache: "force-cache" });
    if (!res.ok) return null;
    const json = (await res.json()) as DumpFile;
    if (!json?.pages) return null;
    return json;
  } catch {
    // Bundled dump missing or malformed — caller will fall back to the
    // remote API. This shouldn't happen in normal deploys but we don't
    // want to crash the reader if it does.
    return null;
  }
}

export function getDump(): Promise<DumpFile | null> {
  if (!dumpPromise) {
    // Only memoise SUCCESSFUL loads. If the fetch fails (or returns a
    // malformed body) we drop the cached promise so the next call can
    // retry — otherwise one transient failure would poison the SPA
    // until a full reload.
    const p = loadDump().then((dump) => {
      if (!dump) dumpPromise = null;
      return dump;
    }).catch((err) => {
      dumpPromise = null;
      throw err;
    });
    dumpPromise = p;
  }
  return dumpPromise;
}

export async function getPageFromDump(
  pageNumber: number,
): Promise<ApiAyah[] | null> {
  const dump = await getDump();
  if (!dump) return null;
  const ayahs = dump.pages[String(pageNumber)];
  return ayahs && ayahs.length > 0 ? ayahs : null;
}
