// Bundled Tafsir Muyassar loader.
//
// The app ships a static `tafsir-muyassar.json` (generated by
// `pnpm --filter @workspace/scripts run build-tafsir-dump`) under the
// artifact's public folder so it serves over the same origin and works
// fully offline once cached by the browser. This means a self-hosted
// instance does NOT need any external API to display tafsir — the
// alquran.cloud per-ayah endpoint is kept only as a last-resort
// fallback for individual ayahs when the bundle is unreachable.
//
// The dump is fetched lazily (and only once per session) the first
// time any ayah's tafsir is requested. The full file is ~2.5 MB; once
// the browser has it, every ayah is an O(1) Map lookup.
//
// Bump CACHE_VERSION whenever the dump shape changes so old IDB
// entries are ignored.

import { get, set, keys, del } from "idb-keyval";

const CACHE_VERSION = 1;
const KEY_PREFIX = `tafsir-muyassar-v${CACHE_VERSION}:`;
const FALLBACK_BASE = "https://api.alquran.cloud/v1/ayah";

interface DumpFile {
  version: number;
  edition: string;
  source: string;
  ayahs: Record<string, string>;
}

let dumpPromise: Promise<DumpFile | null> | null = null;

export function resetTafsirCache(): void {
  dumpPromise = null;
}

function dumpUrl(): string {
  const base = import.meta.env.BASE_URL ?? "/";
  return `${base}tafsir-muyassar.json`;
}

async function loadDump(): Promise<DumpFile | null> {
  try {
    const res = await fetch(dumpUrl(), { cache: "force-cache" });
    if (!res.ok) return null;
    const json = (await res.json()) as DumpFile;
    if (!json?.ayahs) return null;
    return json;
  } catch {
    return null;
  }
}

function getDump(): Promise<DumpFile | null> {
  if (!dumpPromise) {
    const p = loadDump()
      .then((dump) => {
        if (!dump) dumpPromise = null;
        return dump;
      })
      .catch((err) => {
        dumpPromise = null;
        throw err;
      });
    dumpPromise = p;
  }
  return dumpPromise;
}

function idbKey(globalAyahNumber: number): string {
  return `${KEY_PREFIX}${globalAyahNumber}`;
}

/**
 * Resolve a single ayah's Tafsir Muyassar text via a layered fallback
 * chain that mirrors the Reader's quran-text loading:
 *   1. Per-ayah IndexedDB cache (fastest, survives reloads).
 *   2. Bundled local dump (offline-capable, ships with the app).
 *   3. alquran.cloud per-ayah endpoint (last-resort, only when both
 *      above fail — a self-hosted fork without internet still works).
 *
 * Successful lookups from (2) and (3) are written back to IDB so the
 * next read is instant.
 */
export async function getAyahTafsir(globalAyahNumber: number): Promise<string | null> {
  // 1) IDB warm cache
  try {
    const cached = await get<string>(idbKey(globalAyahNumber));
    if (typeof cached === "string" && cached.length > 0) return cached;
  } catch {
    // Quota / private-mode failures are non-fatal.
  }

  // 2) Bundled local dump
  const dump = await getDump();
  const fromDump = dump?.ayahs[String(globalAyahNumber)];
  if (typeof fromDump === "string" && fromDump.length > 0) {
    void set(idbKey(globalAyahNumber), fromDump).catch(() => {});
    return fromDump;
  }

  // 3) Remote fallback — single ayah, only used if the bundled dump is
  // unreachable AND IDB had no warm copy.
  try {
    const res = await fetch(`${FALLBACK_BASE}/${globalAyahNumber}/ar.muyassar`);
    if (!res.ok) return null;
    const json = (await res.json()) as { code?: number; data?: { text?: string } };
    const text = json?.data?.text;
    if (typeof text === "string" && text.length > 0) {
      void set(idbKey(globalAyahNumber), text).catch(() => {});
      return text;
    }
  } catch {
    // Offline / blocked.
  }
  return null;
}

/**
 * Drop entries from older cache versions so storage doesn't grow
 * unbounded across schema bumps. Mirrors purgeStaleCacheVersions in
 * quran-page-cache.ts.
 */
export async function purgeStaleTafsirVersions(): Promise<void> {
  try {
    const all = await keys();
    await Promise.all(
      all
        .filter(
          (k) =>
            typeof k === "string" &&
            k.startsWith("tafsir-muyassar-v") &&
            !k.startsWith(KEY_PREFIX),
        )
        .map((k) => del(k)),
    );
  } catch {
    // ignore
  }
}
