// Bundled word-by-word loader.
//
// The app ships a static `wbw.json` (generated by
// `pnpm --filter @workspace/scripts run build-wbw-dump`) under the
// artifact's public folder so it serves over the same origin and works
// fully offline once cached by the browser. The remote quran.com API
// is kept only as a last-resort fallback for individual ayahs when the
// bundle is unreachable.
//
// Bump CACHE_VERSION whenever the dump shape changes so old IDB
// entries are ignored.

import { get, set, keys, del } from "idb-keyval";

const CACHE_VERSION = 1;
const KEY_PREFIX = `wbw-v${CACHE_VERSION}:`;
const FALLBACK_BASE = "https://api.quran.com/api/v4/verses/by_key";

export interface WbwWord {
  /** Arabic Uthmani text for this word. */
  ar: string;
  /** English gloss; "" when missing on source. */
  en: string;
  /** Latin transliteration; "" when missing on source. */
  tr: string;
}

interface DumpFile {
  version: number;
  edition: string;
  source: string;
  ayahs: Record<string, WbwWord[]>;
}

let dumpPromise: Promise<DumpFile | null> | null = null;

export function resetWbwCache(): void {
  dumpPromise = null;
}

function dumpUrl(): string {
  const base = import.meta.env.BASE_URL ?? "/";
  return `${base}wbw.json`;
}

async function loadDump(): Promise<DumpFile | null> {
  try {
    const res = await fetch(dumpUrl(), { cache: "force-cache" });
    if (!res.ok) return null;
    const json = (await res.json()) as DumpFile;
    if (!json?.ayahs) return null;
    return json;
  } catch {
    return null;
  }
}

function getDump(): Promise<DumpFile | null> {
  if (!dumpPromise) {
    const p = loadDump()
      .then((dump) => {
        if (!dump) dumpPromise = null;
        return dump;
      })
      .catch((err) => {
        dumpPromise = null;
        throw err;
      });
    dumpPromise = p;
  }
  return dumpPromise;
}

function idbKey(globalAyahNumber: number): string {
  return `${KEY_PREFIX}${globalAyahNumber}`;
}

/** Convert a global ayah number to a quran.com verse_key like "2:255". */
function verseKeyFromGlobal(
  globalAyahNumber: number,
  surahNumber: number,
  ayahNumberInSurah: number,
): string {
  // Both are needed; we accept them rather than re-deriving so we don't
  // have to re-walk the surah-length table here. globalAyahNumber kept
  // in the signature keeps the API symmetrical with getAyahTafsir.
  void globalAyahNumber;
  return `${surahNumber}:${ayahNumberInSurah}`;
}

/**
 * Resolve a single ayah's word-by-word breakdown via a layered
 * fallback chain that mirrors the Reader's quran-text loading:
 *   1. Per-ayah IndexedDB cache (fastest, survives reloads).
 *   2. Bundled local dump (offline-capable, ships with the app).
 *   3. quran.com per-verse endpoint (last-resort, only when both
 *      above fail — a self-hosted fork without internet still works
 *      from the bundle).
 *
 * Successful lookups from (2) and (3) are written back to IDB so the
 * next read is instant.
 */
export async function getAyahWbw(args: {
  globalAyahNumber: number;
  surahNumber: number;
  ayahNumberInSurah: number;
}): Promise<WbwWord[] | null> {
  const { globalAyahNumber, surahNumber, ayahNumberInSurah } = args;

  // 1) IDB warm cache
  try {
    const cached = await get<WbwWord[]>(idbKey(globalAyahNumber));
    if (Array.isArray(cached) && cached.length > 0) return cached;
  } catch {
    // ignore
  }

  // 2) Bundled local dump
  const dump = await getDump();
  const fromDump = dump?.ayahs[String(globalAyahNumber)];
  if (Array.isArray(fromDump) && fromDump.length > 0) {
    void set(idbKey(globalAyahNumber), fromDump).catch(() => {});
    return fromDump;
  }

  // 3) Remote fallback — single ayah only.
  try {
    const key = verseKeyFromGlobal(globalAyahNumber, surahNumber, ayahNumberInSurah);
    const url =
      `${FALLBACK_BASE}/${encodeURIComponent(key)}` +
      `?language=en&words=true&word_fields=text_uthmani&word_translation_language=en`;
    const res = await fetch(url);
    if (!res.ok) return null;
    const json = (await res.json()) as {
      verse?: {
        words?: Array<{
          char_type_name?: string;
          text_uthmani?: string;
          text?: string;
          translation?: { text?: string };
          transliteration?: { text?: string };
        }>;
      };
    };
    const out: WbwWord[] = [];
    for (const w of json.verse?.words ?? []) {
      if (w.char_type_name && w.char_type_name !== "word") continue;
      const ar = w.text_uthmani ?? w.text ?? "";
      if (!ar) continue;
      out.push({
        ar,
        en: w.translation?.text ?? "",
        tr: w.transliteration?.text ?? "",
      });
    }
    if (out.length > 0) {
      void set(idbKey(globalAyahNumber), out).catch(() => {});
      return out;
    }
  } catch {
    // Offline / blocked.
  }
  return null;
}

export async function purgeStaleWbwVersions(): Promise<void> {
  try {
    const all = await keys();
    await Promise.all(
      all
        .filter(
          (k) =>
            typeof k === "string" && k.startsWith("wbw-v") && !k.startsWith(KEY_PREFIX),
        )
        .map((k) => del(k)),
    );
  } catch {
    // ignore
  }
}
